services:
  microservice-users:
    build: ./microservice-users
    volumes:
      - ./microservice-users/code:/code
      - /code/node_modules
    env_file:
      - ./.env    

  # microservice-timer:
  #   build: ./microservice-timer
  #   volumes:
  #     - ./microservice-timer/code:/code
  #     - /code/node_modules
  #   env_file:
  #     - ./.env    

  microservice-statistics:
    build: ./microservice-statistics
    volumes:
      - ./microservice-statistics/code:/code
      - /code/node_modules
    env_file:
      - ./.env    

  microservice-shop:
    build: ./microservice-shop
    volumes:
      - ./microservice-shop/code:/code
      - /code/node_modules
    env_file:
      - ./.env    

  microservice-goals-milestones:
    build: ./microservice-goals-milestones
    volumes:
      - ./microservice-goals-milestones/code:/code
      - /code/node_modules
    env_file:
      - ./.env    

  apigateway:
    build: ./apigateway
    volumes:
      - ./apigateway/code:/code
      - /code/node_modules
    env_file:
      - ./.env    
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}" # Only expose the API Gateway
    depends_on:
      - microservice-users
      - microservice-statistics
      - microservice-shop
      - microservice-goals-milestones

volumes:
  mysql-data:
