swagger: "2.0"
info:
  title: "Badges Microservice API"
  version: "1.0.0"
paths:
  /:
    get:
      summary: "Retrieve a list of badges"
      tags:
        - Badges
      responses:
        200:
          description: "A list of badges"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    badgeID:
                      type: integer
                      description: "The badge ID"
                    badgeName:
                      type: string
                      description: "The badge name"
                    badgeDescription:
                      type: string
                      description: "The badge description"
                    badgeImage:
                      type: string
                      description: "The badge image URL"
  /{badgeID}:
    get:
      summary: "Retrieve a specific badge"
      tags:
        - Badges
      parameters:
        - in: path
          name: badgeID
          required: true
          description: "The badge ID"
          schema:
            type: integer
      responses:
        200:
          description: "A badge item"
          content:
            application/json:
              schema:
                type: object
                properties:
                  badgeID:
                    type: integer
                    description: "The badge ID"
                  badgeName:
                    type: string
                    description: "The badge name"
                  badgeDescription:
                    type: string
                    description: "The badge description"
                  badgeImage:
                    type: string
                    description: "The badge image URL"
        404:
          description: "Badge item not found"
  /{badgeID}/update:
    put:
      summary: "Update a specific badge"
      tags:
        - Badges
      parameters:
        - in: path
          name: badgeID
          required: true
          description: "The badge ID"
          schema:
            type: integer
        - in: query
          name: badgeName
          description: "The new badge name"
          schema:
            type: string
        - in: query
          name: badgeDescription
          description: "The new badge description"
          schema:
            type: string
        - in: query
          name: badgeImage
          description: "The new badge image URL"
          schema:
            type: string
      responses:
        200:
          description: "Badge item updated successfully"
        400:
          description: "No fields to update"
        404:
          description: "Badge item not found"
  /{badgeID}/delete:
    delete:
      summary: "Delete a specific badge"
      tags:
        - Badges
      parameters:
        - in: path
          name: badgeID
          required: true
          description: "The badge ID"
          schema:
            type: integer
      responses:
        200:
          description: "Badge item deleted"
        404:
          description: "Badge item not found"
  /add:
    post:
      summary: "Add a new badge"
      tags:
        - Badges
      parameters:
        - in: query
          name: badgeName
          required: true
          description: "The badge name"
          schema:
            type: string
        - in: query
          name: badgeDescription
          required: true
          description: "The badge description"
          schema:
            type: string
        - in: query
          name: badgeImage
          required: true
          description: "The badge image URL"
          schema:
            type: string
      responses:
        201:
          description: "Badge item added successfully"
        400:
          description: "All fields (badgeName, badgeDescription, badgeImage) are required"
        500:
          description: "An error occurred while adding the badge item"
definitions:
  Badge:
    type: object
    properties:
      badgeID:
        type: integer
        description: "The badge ID"
      badgeName:
        type: string
        description: "The badge name"
      badgeDescription:
        type: string
        description: "The badge description"
      badgeImage:
        type: string
        description: "The badge image URL"
