swagger: "2.0"
info:
  title: "Badges Microservice API"
  version: "1.0.0"
paths:
  /:
    get:
      summary: "Retrieve a list of badges"
      tags:
        - Badges
      responses:
        200:
          description: "A list of badges"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    itemID:
                      type: integer
                      description: "The badge ID"
                    itemValue:
                      type: string
                      description: "The badge value"
                    itemImage:
                      type: string
                      description: "The badge image URL"
  /{itemID}:
    get:
      summary: "Retrieve a specific badge"
      tags:
        - Badges
      parameters:
        - in: path
          name: itemID
          required: true
          description: "The badge ID"
          schema:
            type: integer
      responses:
        200:
          description: "A badge item"
          content:
            application/json:
              schema:
                type: object
                properties:
                  itemID:
                    type: integer
                    description: "The badge ID"
                  itemValue:
                    type: string
                    description: "The badge value"
                  itemImage:
                    type: string
                    description: "The badge image URL"
        404:
          description: "Badge item not found"
  /{itemID}/update:
    put:
      summary: "Update a specific badge"
      tags:
        - Badges
      parameters:
        - in: path
          name: itemID
          required: true
          description: "The badge ID"
          schema:
            type: integer
        - in: query
          name: itemValue
          description: "The new badge value"
          schema:
            type: string
        - in: query
          name: itemImage
          description: "The new badge image URL"
          schema:
            type: string
      responses:
        200:
          description: "Badge item updated successfully"
        400:
          description: "No fields to update"
        404:
          description: "Badge item not found"
  /{itemID}/delete:
    delete:
      summary: "Delete a specific badge"
      tags:
        - Badges
      parameters:
        - in: path
          name: itemID
          required: true
          description: "The badge ID"
          schema:
            type: integer
      responses:
        200:
          description: "Badge item deleted"
        404:
          description: "Badge item not found"
definitions:
  Badge:
    type: object
    properties:
      itemID:
        type: integer
        description: "The badge ID"
      itemValue:
        type: string
        description: "The badge value"
      itemImage:
        type: string
        description: "The badge image URL"
